[package]
name = "spinoza"
version = "0.1.0"
edition = "2021"

[features]
default = ["double"]
single = []
double = []

[dependencies]
bytemuck = "1.13.1"
clap = { version = "4.2.4", features = ["derive"] }
comfy-table = "6.1.4"
env_logger = "0.10.0"
lazy_static = "1.4.0"
num_cpus = "1.15.0"
once_cell = "1.17.1"
rand = "0.8.5"
rayon = "1.7.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "benchmark"
harness = false
